import type { BulkJob } from "./bulk-job";

/**
 * Default chunk size for QStash fan-out: 15 dispatchers per worker.
 * Tuned so each worker finishes well under the QStash 15-minute invocation
 * cap — PDF concurrency 4 on a 15-person slice completes in <2 min with
 * comfortable headroom.
 */
export const DEFAULT_CHUNK_SIZE = 15;

export type ChunkStatus = "pending" | "running" | "done" | "failed";

export interface ChunkState {
  index: number;
  dispatcherIds: string[];
  status: ChunkStatus;
  /** R2 key of the part ZIP, set once status flips to `done`. */
  r2Key?: string;
  /** File count generated by this chunk (may be < dispatcherIds.length if
   *  some errored). */
  fileCount?: number;
  /** Human-readable error when status === `failed`. */
  error?: string;
}

/**
 * Splits a dispatcher ID list into N chunks of `chunkSize` each. The last
 * chunk may be smaller. Pure, no side effects.
 */
export function splitDispatchers(
  dispatcherIds: string[],
  chunkSize: number = DEFAULT_CHUNK_SIZE,
): ChunkState[] {
  if (chunkSize <= 0) throw new Error("chunkSize must be > 0");
  if (dispatcherIds.length === 0) return [];

  const chunks: ChunkState[] = [];
  for (let i = 0; i < dispatcherIds.length; i += chunkSize) {
    chunks.push({
      index: chunks.length,
      dispatcherIds: dispatcherIds.slice(i, i + chunkSize),
      status: "pending",
    });
  }
  return chunks;
}

/**
 * Returns true iff every chunk has reached a terminal state. Used by
 * `/worker/chunk` to decide whether to publish the finalize message.
 */
export function allChunksTerminal(chunks: ChunkState[]): boolean {
  return chunks.length > 0 && chunks.every((c) => c.status === "done" || c.status === "failed");
}

/**
 * Returns `done` chunk count — the Downloads Panel uses this to drive the
 * chunk-level progress bar when a fan-out job has no per-file counter yet.
 */
export function countDoneChunks(chunks: ChunkState[]): number {
  return chunks.filter((c) => c.status === "done").length;
}

/** Parts are written under `bulk-exports/{agentId}/{jobId}/parts/{index}.zip`. */
export function partR2Key(job: Pick<BulkJob, "agentId" | "jobId">, chunkIndex: number): string {
  return `bulk-exports/${job.agentId}/${job.jobId}/parts/${chunkIndex}.zip`;
}
